In [5]:
pip install torch

In [8]:
import torch
import numpy as np

In [9]:
import torch.nn.functional as F

# Soft vs Hard?

In [10]:
test = torch.from_numpy(np.array([[1,2,3],[10,5,1],[9,8,7]]).astype(np.float))

In [11]:
test.shape

torch.Size([3, 3])

In [12]:
result_soft = F.gumbel_softmax(test)

In [13]:
print(result_soft)

tensor([[2.2031e-02, 4.6976e-02, 9.3099e-01],
        [9.9402e-01, 5.9503e-03, 3.1650e-05],
        [6.4901e-01, 2.9863e-01, 5.2354e-02]], dtype=torch.float64)


They will be probability distributions that sum to 1 across dim.

In [14]:
result_hard = F.gumbel_softmax(test, hard=True) # one-hot으로 바뀌어 나온다.

In [15]:
print(result_hard)

tensor([[0., 1., 0.],
        [1., 0., 0.],
        [1., 0., 0.]], dtype=torch.float64)


# Tau (Temperature)

In [16]:
import matplotlib.pyplot as plt

In [17]:
tem_list = [0.1, 0.5, 1.0, 2.0, 10.0]

In [18]:
for tau in tem_list:
    print('tau : ', tau)
    sum_array = torch.from_numpy(np.zeros(result_hard.shape))
    for n in range(1000):
        result_hard = F.gumbel_softmax(test, hard=True, tau=tau)
        sum_array += result_hard
    print(sum_array, '\n')

tau :  0.1
tensor([[106., 244., 650.],
        [990.,  10.,   0.],
        [676., 233.,  91.]], dtype=torch.float64) 

tau :  0.5
tensor([[ 85., 253., 662.],
        [994.,   6.,   0.],
        [684., 220.,  96.]], dtype=torch.float64) 

tau :  1.0
tensor([[ 90., 244., 666.],
        [990.,   9.,   1.],
        [683., 234.,  83.]], dtype=torch.float64) 

tau :  2.0
tensor([[ 99., 233., 668.],
        [996.,   4.,   0.],
        [652., 248., 100.]], dtype=torch.float64) 

tau :  10.0
tensor([[ 99., 223., 678.],
        [996.,   4.,   0.],
        [663., 244.,  93.]], dtype=torch.float64) 



가장 많이 나와야 하는 부분들이 tau가 커질수록 적게 나오는 모습을 볼 수 있다! 이는 tau 크기에 의해 고르게 분산되는, 뽑힌다는 것을 알 수 있다.

# Dim

In [26]:
for dim_num in range(-2,2):
    print(dim_num)
    result_hard = F.gumbel_softmax(test, hard=True, dim=dim_num)
    print(result_hard, '\n')

-2
tensor([[0., 0., 0.],
        [1., 0., 0.],
        [0., 1., 1.]], dtype=torch.float64) 

-1
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 1., 0.]], dtype=torch.float64) 

0
tensor([[0., 0., 0.],
        [1., 0., 0.],
        [0., 1., 1.]], dtype=torch.float64) 

1
tensor([[0., 0., 1.],
        [1., 0., 0.],
        [1., 0., 0.]], dtype=torch.float64) 

